# SPDX-License-Identifier: MIT-0

"""Contract tests for app-owned ChatGPT subscription authentication.

The finished product must not require a separately installed Codex CLI or ask
an end user to prepare credential files. These tests define the temporary
standalone boundary instead: txt2crs starts the bundled Codex app server,
returns a device-code challenge that a frontend can render, and keeps all
credential bytes inside an application-owned ``CODEX_HOME``.
"""

from dataclasses import dataclass
from pathlib import Path
from threading import Event
from types import SimpleNamespace
from typing import Any

import pytest
from openai_codex import CodexConfig

from txt2crs.ai.system_authentication import (
    DedicatedSystemAuthenticator,
    SystemAuthenticationError,
    SystemAuthenticationState,
)


@dataclass(slots=True)
class FakeLoginNotification:
    """SDK-shaped completion notification returned by a fake login handle."""

    success: bool
    error: str | None = None


class FakeDeviceCodeLoginHandle:
    """Controllable SDK login handle that never contains real credentials."""

    login_id = "login-123"
    verification_url = "https://auth.openai.com/codex/device"
    user_code = "ABCD-1234"

    def __init__(
        self,
        *,
        notification: FakeLoginNotification,
        wait_gate: Event | None = None,
    ) -> None:
        self._notification = notification
        self._wait_gate = wait_gate
        self.cancelled = False

    def wait(self) -> FakeLoginNotification:
        """Wait for the test-controlled user action, then return completion."""

        if self._wait_gate is not None:
            self._wait_gate.wait(timeout=2)
        return self._notification

    def cancel(self) -> object:
        """Record cancellation without exposing an SDK-specific response."""

        self.cancelled = True
        if self._wait_gate is not None:
            self._wait_gate.set()
        return object()


class FakeAuthenticationClient:
    """Small structural double for the public Codex authentication methods."""

    def __init__(
        self,
        *,
        account_type: str | None = "chatgpt",
        login_success: bool = True,
        provider_error: str | None = None,
        wait_gate: Event | None = None,
    ) -> None:
        self.account_type = account_type
        self.login_handle = FakeDeviceCodeLoginHandle(
            notification=FakeLoginNotification(
                success=login_success,
                error=provider_error,
            ),
            wait_gate=wait_gate,
        )
        self.account_refresh_requested = False
        self.logged_out = False
        self.closed = False

    def login_chatgpt_device_code(self) -> FakeDeviceCodeLoginHandle:
        """Return the fake challenge generated by the bundled app server."""

        return self.login_handle

    def account(self, *, refresh_token: bool = False) -> object:
        """Return only an SDK-shaped account union, never credential material."""

        self.account_refresh_requested = refresh_token
        account = (
            None
            if self.account_type is None
            else SimpleNamespace(
                root=SimpleNamespace(type=self.account_type),
            )
        )
        return SimpleNamespace(account=account)

    def logout(self) -> None:
        """Record a request to clear the dedicated system credential cache."""

        self.logged_out = True

    def close(self) -> None:
        """Record deterministic app-server cleanup."""

        self.closed = True


def test_device_code_login_is_frontend_ready_and_verifies_chatgpt_account() -> None:
    """The app receives a challenge and Codex owns the complete OAuth exchange."""

    wait_gate = Event()
    fake_client = FakeAuthenticationClient(wait_gate=wait_gate)
    authenticator = DedicatedSystemAuthenticator(client_factory=lambda: fake_client)

    challenge = authenticator.start_device_code_login()

    assert challenge.state is SystemAuthenticationState.waiting_for_user
    assert challenge.verification_url == "https://auth.openai.com/codex/device"
    assert challenge.user_code == "ABCD-1234"
    assert "token" not in challenge.model_dump_json().casefold()

    wait_gate.set()
    completed = authenticator.wait_for_current_attempt(timeout_seconds=2)

    assert completed.state is SystemAuthenticationState.authenticated
    assert completed.verification_url is None
    assert completed.user_code is None
    assert fake_client.account_refresh_requested is True
    assert fake_client.closed is True


def test_failed_login_redacts_provider_details_from_frontend_status() -> None:
    """Provider errors and credential-like text never cross the app boundary."""

    fake_client = FakeAuthenticationClient(
        login_success=False,
        provider_error="Bearer extremely-sensitive-provider-token",
    )
    authenticator = DedicatedSystemAuthenticator(client_factory=lambda: fake_client)

    authenticator.start_device_code_login()
    completed = authenticator.wait_for_current_attempt(timeout_seconds=2)
    serialized_status = completed.model_dump_json()

    assert completed.state is SystemAuthenticationState.failed
    assert "extremely-sensitive-provider-token" not in serialized_status
    assert "bearer" not in serialized_status.casefold()
    assert fake_client.closed is True


def test_api_key_account_cannot_satisfy_subscription_authentication() -> None:
    """A successful ceremony still fails when Codex reports API-key mode."""

    fake_client = FakeAuthenticationClient(account_type="apiKey")
    authenticator = DedicatedSystemAuthenticator(client_factory=lambda: fake_client)

    authenticator.start_device_code_login()
    completed = authenticator.wait_for_current_attempt(timeout_seconds=2)

    assert completed.state is SystemAuthenticationState.failed
    assert "ChatGPT subscription" in completed.message
    assert fake_client.closed is True


def test_device_code_login_rejects_non_openai_verification_origin() -> None:
    """A compromised provider response cannot turn setup into a phishing link."""

    fake_client = FakeAuthenticationClient()
    fake_client.login_handle.verification_url = "https://attacker.example/device"
    authenticator = DedicatedSystemAuthenticator(client_factory=lambda: fake_client)

    with pytest.raises(
        SystemAuthenticationError,
        match="could not be started",
    ):
        authenticator.start_device_code_login()

    assert fake_client.closed is True
    assert authenticator.current_status().state is SystemAuthenticationState.failed


def test_create_uses_bundled_runtime_and_isolated_file_credentials(
    tmp_path: Path,
) -> None:
    """No external CLI, shared home, API key, or OS keyring is required."""

    captured_configs: list[CodexConfig] = []
    wait_gate = Event()
    fake_client = FakeAuthenticationClient(wait_gate=wait_gate)

    def build_fake_client(config: CodexConfig) -> Any:
        """Capture the SDK launch contract before returning the fake client."""

        captured_configs.append(config)
        return fake_client

    worker_directory = tmp_path / "worker"
    codex_home = tmp_path / "dedicated-system-codex-home"
    authenticator = DedicatedSystemAuthenticator.create(
        worker_directory=worker_directory,
        codex_home=codex_home,
        parent_environment={
            "PATH": "/usr/bin",
            "OPENAI_API_KEY": "must-not-reach-codex",
            "codex_api_key": "case-variant-secret",
            "TAVILY_API_KEY": "research-process-only",
        },
        client_builder=build_fake_client,
    )

    authenticator.start_device_code_login()
    config = captured_configs[0]

    assert config.codex_bin is None
    assert config.env is not None
    assert config.env["CODEX_HOME"] == str(codex_home.resolve())
    assert config.env["OPENAI_API_KEY"] == ""
    assert config.env["codex_api_key"] == ""
    assert config.env["TAVILY_API_KEY"] == ""
    assert 'forced_login_method="chatgpt"' in config.config_overrides
    assert 'cli_auth_credentials_store="file"' in config.config_overrides
    assert "mcp_servers={}" in config.config_overrides
    assert worker_directory.stat().st_mode & 0o777 == 0o700
    assert codex_home.stat().st_mode & 0o777 == 0o700

    authenticator.close()
    assert fake_client.login_handle.cancelled is True
    assert fake_client.closed is True
