// This file is auto-generated by @hey-api/openapi-ts

export const Body_jobs_submit_job_uploadSchema = {
  properties: {
    metadata: {
      type: "string",
      maxLength: 262144,
      minLength: 2,
      title: "Metadata",
      description: "Strict JSON course preferences, consent, and age group.",
    },
    file: {
      type: "string",
      contentMediaType: "application/octet-stream",
      title: "File",
      description: "One bounded PDF, DOCX, or PPTX source.",
    },
  },
  type: "object",
  required: ["metadata", "file"],
  title: "Body_jobs-submit_job_upload",
} as const

export const Body_login_login_access_tokenSchema = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: "string",
          pattern: "^password$",
        },
        {
          type: "null",
        },
      ],
      title: "Grant Type",
    },
    username: {
      type: "string",
      title: "Username",
    },
    password: {
      type: "string",
      format: "password",
      title: "Password",
    },
    scope: {
      type: "string",
      title: "Scope",
      default: "",
    },
    client_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Id",
    },
    client_secret: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      format: "password",
      title: "Client Secret",
    },
  },
  type: "object",
  required: ["username", "password"],
  title: "Body_login-login_access_token",
} as const

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const

export const HealthCheckResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
    },
    timestamp: {
      type: "string",
      title: "Timestamp",
    },
    database: {
      type: "string",
      title: "Database",
    },
    version: {
      type: "string",
      title: "Version",
    },
  },
  type: "object",
  required: ["status", "timestamp", "database", "version"],
  title: "HealthCheckResponse",
} as const

export const ItemCreateSchema = {
  properties: {
    title: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    source_url: {
      anyOf: [
        {
          type: "string",
          maxLength: 2048,
        },
        {
          type: "null",
        },
      ],
      title: "Source Url",
    },
    content: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Content",
    },
    content_type: {
      anyOf: [
        {
          type: "string",
          const: "general",
          maxLength: 50,
        },
        {
          type: "null",
        },
      ],
      title: "Content Type",
    },
    item_metadata: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Item Metadata",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["title"],
  title: "ItemCreate",
  description:
    "Request body for creating a new item.\n\nRequires title, all other fields are optional. Rejects unknown fields\nto prevent API misuse.",
} as const

export const ItemPublicSchema = {
  properties: {
    title: {
      type: "string",
      maxLength: 255,
      minLength: 1,
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    source_url: {
      anyOf: [
        {
          type: "string",
          maxLength: 2048,
        },
        {
          type: "null",
        },
      ],
      title: "Source Url",
    },
    content: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Content",
    },
    content_type: {
      anyOf: [
        {
          type: "string",
          const: "general",
          maxLength: 50,
        },
        {
          type: "null",
        },
      ],
      title: "Content Type",
    },
    item_metadata: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Item Metadata",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    owner_id: {
      type: "string",
      format: "uuid",
      title: "Owner Id",
    },
    created_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Created At",
    },
  },
  type: "object",
  required: ["title", "id", "owner_id"],
  title: "ItemPublic",
} as const

export const ItemUpdateSchema = {
  properties: {
    title: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Title",
    },
    description: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    source_url: {
      anyOf: [
        {
          type: "string",
          maxLength: 2048,
        },
        {
          type: "null",
        },
      ],
      title: "Source Url",
    },
    content: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Content",
    },
    content_type: {
      anyOf: [
        {
          type: "string",
          const: "general",
        },
        {
          type: "null",
        },
      ],
      title: "Content Type",
    },
    item_metadata: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Item Metadata",
    },
  },
  additionalProperties: false,
  type: "object",
  title: "ItemUpdate",
  description:
    "Request body for updating an item.\n\nAll fields are optional for partial updates. Rejects unknown fields\nto prevent API misuse.",
} as const

export const ItemsPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/ItemPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "ItemsPublic",
} as const

export const JobAcceptedPublicSchema = {
  properties: {
    schema_version: {
      type: "string",
      const: "1.0",
      title: "Schema Version",
    },
    job_id: {
      type: "string",
      maxLength: 128,
      minLength: 1,
      pattern: "^[A-Za-z0-9][A-Za-z0-9._:-]*$",
      title: "Job Id",
    },
    status: {
      type: "string",
      const: "accepted",
      title: "Status",
    },
    revision: {
      type: "integer",
      minimum: 0,
      title: "Revision",
    },
    status_url: {
      type: "string",
      maxLength: 160,
      minLength: 14,
      pattern: "^/api/v1/jobs/[A-Za-z0-9][A-Za-z0-9._:-]*$",
      title: "Status Url",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["schema_version", "job_id", "status", "revision", "status_url"],
  title: "JobAcceptedPublic",
  description:
    "Allowlisted response returned only after a durable package commit.",
} as const

export const JobLearnerAgeGroupSchema = {
  type: "string",
  enum: ["minor", "adult", "not_provided"],
  title: "JobLearnerAgeGroup",
  description: "Privacy-minimized age context passed to package policy.",
} as const

export const JobLearningLevelSchema = {
  type: "string",
  enum: ["auto", "beginner", "intermediate", "advanced", "mixed"],
  title: "JobLearningLevel",
  description: "Reviewed P0 learner-selectable depth intent.",
} as const

export const JobPreferencesSchema = {
  properties: {
    level: {
      $ref: "#/components/schemas/JobLearningLevel",
    },
    audience: {
      anyOf: [
        {
          type: "string",
          maxLength: 500,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Audience",
    },
    prior_knowledge: {
      anyOf: [
        {
          type: "string",
          maxLength: 2000,
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "Prior Knowledge",
    },
    learning_goals: {
      items: {
        type: "string",
        maxLength: 500,
        minLength: 3,
      },
      type: "array",
      maxItems: 10,
      title: "Learning Goals",
    },
    language: {
      type: "string",
      maxLength: 35,
      minLength: 2,
      title: "Language",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "level",
    "audience",
    "prior_knowledge",
    "learning_goals",
    "language",
  ],
  title: "JobPreferences",
  description:
    "Finite learning intent; all other generation defaults are server-owned.",
} as const

export const JobSubmissionRequestSchema = {
  properties: {
    preferences: {
      $ref: "#/components/schemas/JobPreferences",
    },
    consent_to_ai_processing: {
      type: "boolean",
      const: true,
      title: "Consent To Ai Processing",
    },
    learner_age_group: {
      $ref: "#/components/schemas/JobLearnerAgeGroup",
    },
    input: {
      oneOf: [
        {
          $ref: "#/components/schemas/PromptJobInput",
        },
        {
          $ref: "#/components/schemas/TextJobInput",
        },
        {
          $ref: "#/components/schemas/UrlJobInput",
        },
        {
          $ref: "#/components/schemas/YouTubeJobInput",
        },
      ],
      title: "Input",
      discriminator: {
        propertyName: "type",
        mapping: {
          prompt: "#/components/schemas/PromptJobInput",
          text: "#/components/schemas/TextJobInput",
          url: "#/components/schemas/UrlJobInput",
          youtube: "#/components/schemas/YouTubeJobInput",
        },
      },
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "preferences",
    "consent_to_ai_processing",
    "learner_age_group",
    "input",
  ],
  title: "JobSubmissionRequest",
  description: "Strict JSON request with one discriminated source input.",
} as const

export const MessageSchema = {
  properties: {
    message: {
      type: "string",
      title: "Message",
    },
  },
  type: "object",
  required: ["message"],
  title: "Message",
} as const

export const NewPasswordSchema = {
  properties: {
    token: {
      type: "string",
      title: "Token",
    },
    new_password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "New Password",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["token", "new_password"],
  title: "NewPassword",
  description:
    "Request body for password reset completion.\n\nSubmitted after user clicks the password reset link. Token is from\nthe email link, new_password must meet strength requirements.",
} as const

export const PasswordRecoveryRequestSchema = {
  properties: {
    email: {
      type: "string",
      maxLength: 255,
      format: "email",
      title: "Email",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["email"],
  title: "PasswordRecoveryRequest",
  description:
    "Request body for initiating password recovery.\n\nUses JSON body input (instead of URL path parameters) to avoid exposing\nemail addresses in route paths captured by access logs and browser history.",
} as const

export const PromptJobInputSchema = {
  properties: {
    type: {
      type: "string",
      const: "prompt",
      title: "Type",
    },
    value: {
      type: "string",
      maxLength: 10000,
      minLength: 3,
      title: "Value",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["type", "value"],
  title: "PromptJobInput",
  description: "A short topic or course-generation instruction.",
} as const

export const ReadinessCheckStateSchema = {
  type: "string",
  enum: ["ready", "unavailable"],
  title: "ReadinessCheckState",
  description: "Coarse state for one safe shell readiness dimension.",
} as const

export const ReadinessStatusSchema = {
  type: "string",
  enum: ["ready", "degraded", "unavailable"],
  title: "ReadinessStatus",
  description: "Overall cached state presented to later API schemas.",
} as const

export const SystemAuthenticationPublicSchema = {
  properties: {
    state: {
      $ref: "#/components/schemas/SystemAuthenticationState",
    },
    verification_url: {
      anyOf: [
        {
          type: "string",
          maxLength: 2048,
        },
        {
          type: "null",
        },
      ],
      title: "Verification Url",
    },
    user_code: {
      anyOf: [
        {
          type: "string",
          maxLength: 64,
          minLength: 4,
          pattern: "^[A-Za-z0-9-]+$",
        },
        {
          type: "null",
        },
      ],
      title: "User Code",
    },
    message: {
      type: "string",
      maxLength: 500,
      minLength: 1,
      title: "Message",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["state", "verification_url", "user_code", "message"],
  title: "SystemAuthenticationPublic",
  description:
    "Validated challenge or terminal state with no account/token data.",
} as const

export const SystemAuthenticationStateSchema = {
  type: "string",
  enum: ["signed_out", "waiting_for_user", "authenticated", "failed"],
  title: "SystemAuthenticationState",
  description: "Safe states that an application setup screen may display.",
} as const

export const SystemInputModeSchema = {
  type: "string",
  enum: ["prompt", "text", "url", "youtube", "pdf", "document", "slides"],
  title: "SystemInputMode",
  description: "Finite P0 input modes the generated client may display.",
} as const

export const SystemReadinessChecksPublicSchema = {
  properties: {
    authentication: {
      $ref: "#/components/schemas/ReadinessCheckState",
    },
    model: {
      $ref: "#/components/schemas/ReadinessCheckState",
    },
    research: {
      $ref: "#/components/schemas/ReadinessCheckState",
    },
    storage: {
      $ref: "#/components/schemas/ReadinessCheckState",
    },
    worker: {
      $ref: "#/components/schemas/ReadinessCheckState",
    },
    inputs: {
      $ref: "#/components/schemas/ReadinessCheckState",
    },
    admission: {
      $ref: "#/components/schemas/ReadinessCheckState",
    },
    runtime_ownership: {
      $ref: "#/components/schemas/ReadinessCheckState",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "authentication",
    "model",
    "research",
    "storage",
    "worker",
    "inputs",
    "admission",
    "runtime_ownership",
  ],
  title: "SystemReadinessChecksPublic",
  description: "Coarse dimensions with no infrastructure or provider detail.",
} as const

export const SystemReadinessPublicSchema = {
  properties: {
    schema_version: {
      type: "string",
      const: "1.0",
      title: "Schema Version",
    },
    status: {
      $ref: "#/components/schemas/ReadinessStatus",
    },
    accepting_jobs: {
      type: "boolean",
      title: "Accepting Jobs",
    },
    configured_model_id: {
      type: "string",
      enum: ["gpt-5.6", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna"],
      title: "Configured Model Id",
    },
    enabled_input_modes: {
      items: {
        $ref: "#/components/schemas/SystemInputMode",
      },
      type: "array",
      maxItems: 20,
      title: "Enabled Input Modes",
    },
    checks: {
      $ref: "#/components/schemas/SystemReadinessChecksPublic",
    },
    warnings: {
      items: {
        type: "string",
        maxLength: 500,
        minLength: 1,
      },
      type: "array",
      maxItems: 20,
      title: "Warnings",
    },
    recovery_actions: {
      items: {
        type: "string",
        maxLength: 500,
        minLength: 1,
      },
      type: "array",
      maxItems: 20,
      title: "Recovery Actions",
    },
    checked_at: {
      type: "string",
      format: "date-time",
      title: "Checked At",
    },
    is_fresh: {
      type: "boolean",
      title: "Is Fresh",
    },
  },
  additionalProperties: false,
  type: "object",
  required: [
    "schema_version",
    "status",
    "accepting_jobs",
    "configured_model_id",
    "enabled_input_modes",
    "checks",
    "warnings",
    "recovery_actions",
    "checked_at",
    "is_fresh",
  ],
  title: "SystemReadinessPublic",
  description:
    "HTTP projection of one immutable side-effect-free readiness snapshot.",
} as const

export const TextJobInputSchema = {
  properties: {
    type: {
      type: "string",
      const: "text",
      title: "Type",
    },
    value: {
      type: "string",
      maxLength: 200000,
      minLength: 1,
      title: "Value",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["type", "value"],
  title: "TextJobInput",
  description: "Finite learner-pasted source text.",
} as const

export const TokenSchema = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
      default: "bearer",
    },
  },
  type: "object",
  required: ["access_token"],
  title: "Token",
} as const

export const UpdatePasswordSchema = {
  properties: {
    current_password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "Current Password",
    },
    new_password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "New Password",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["current_password", "new_password"],
  title: "UpdatePassword",
  description:
    "Request body for password change.\n\nRequires both current password (for verification) and new password.\nBoth must meet the 8-128 character length requirement.",
} as const

export const UrlJobInputSchema = {
  properties: {
    value: {
      type: "string",
      maxLength: 2048,
      minLength: 9,
      title: "Value",
    },
    type: {
      type: "string",
      const: "url",
      title: "Type",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["value", "type"],
  title: "UrlJobInput",
  description: "A public URL whose safety and retrieval remain package-owned.",
} as const

export const UserCreateSchema = {
  properties: {
    email: {
      type: "string",
      maxLength: 255,
      format: "email",
      title: "Email",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    is_superuser: {
      type: "boolean",
      title: "Is Superuser",
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "Password",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["email", "password"],
  title: "UserCreate",
  description:
    "Request body for creating a new user (admin endpoint).\n\nValidates email format, password strength, and rejects unknown fields.\nUsed by superusers to create new user accounts with optional permissions.",
} as const

export const UserPublicSchema = {
  properties: {
    email: {
      type: "string",
      maxLength: 255,
      format: "email",
      title: "Email",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    is_superuser: {
      type: "boolean",
      title: "Is Superuser",
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    created_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Created At",
    },
  },
  type: "object",
  required: ["email", "id"],
  title: "UserPublic",
} as const

export const UserRegisterSchema = {
  properties: {
    email: {
      type: "string",
      maxLength: 255,
      format: "email",
      title: "Email",
    },
    password: {
      type: "string",
      maxLength: 128,
      minLength: 8,
      title: "Password",
    },
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["email", "password"],
  title: "UserRegister",
  description:
    "Request body for user self-registration.\n\nPublic endpoint schema with strict validation. Users cannot set\nis_active or is_superuser flags during registration.",
} as const

export const UserUpdateSchema = {
  properties: {
    email: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          format: "email",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    is_superuser: {
      type: "boolean",
      title: "Is Superuser",
      default: false,
    },
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    password: {
      anyOf: [
        {
          type: "string",
          maxLength: 128,
          minLength: 8,
        },
        {
          type: "null",
        },
      ],
      title: "Password",
    },
  },
  additionalProperties: false,
  type: "object",
  title: "UserUpdate",
  description:
    "Request body for updating a user (admin endpoint).\n\nAll fields are optional. Superusers can update any user's details\nincluding email, password, and permission flags.",
} as const

export const UserUpdateMeSchema = {
  properties: {
    full_name: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    email: {
      anyOf: [
        {
          type: "string",
          maxLength: 255,
          format: "email",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
    },
  },
  additionalProperties: false,
  type: "object",
  title: "UserUpdateMe",
  description:
    "Request body for users updating their own profile.\n\nLimited to non-privileged fields (full_name, email). Users cannot\nchange their own is_active or is_superuser status.",
} as const

export const UsersPublicSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/UserPublic",
      },
      type: "array",
      title: "Data",
    },
    count: {
      type: "integer",
      title: "Count",
    },
  },
  type: "object",
  required: ["data", "count"],
  title: "UsersPublic",
} as const

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const

export const YouTubeJobInputSchema = {
  properties: {
    value: {
      type: "string",
      maxLength: 2048,
      minLength: 9,
      title: "Value",
    },
    type: {
      type: "string",
      const: "youtube",
      title: "Type",
    },
  },
  additionalProperties: false,
  type: "object",
  required: ["value", "type"],
  title: "YouTubeJobInput",
  description: "YouTube intent routed through the package URL adapter.",
} as const
