// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client"
import { client } from "./client.gen"
import type {
  DeleteApiV1ItemsByIdData,
  DeleteApiV1ItemsByIdErrors,
  DeleteApiV1ItemsByIdResponses,
  DeleteApiV1UsersByUserIdData,
  DeleteApiV1UsersByUserIdErrors,
  DeleteApiV1UsersByUserIdResponses,
  DeleteApiV1UsersMeData,
  DeleteApiV1UsersMeErrors,
  DeleteApiV1UsersMeResponses,
  GetApiV1ItemsByIdData,
  GetApiV1ItemsByIdErrors,
  GetApiV1ItemsByIdResponses,
  GetApiV1ItemsData,
  GetApiV1ItemsErrors,
  GetApiV1ItemsResponses,
  GetApiV1UsersByUserIdData,
  GetApiV1UsersByUserIdErrors,
  GetApiV1UsersByUserIdResponses,
  GetApiV1UsersData,
  GetApiV1UsersErrors,
  GetApiV1UsersMeData,
  GetApiV1UsersMeErrors,
  GetApiV1UsersMeResponses,
  GetApiV1UsersResponses,
  GetApiV1UtilsHealthCheckData,
  GetApiV1UtilsHealthCheckResponses,
  GetApiV1UtilsHealthData,
  GetApiV1UtilsHealthResponses,
  PatchApiV1UsersByUserIdData,
  PatchApiV1UsersByUserIdErrors,
  PatchApiV1UsersByUserIdResponses,
  PatchApiV1UsersMeData,
  PatchApiV1UsersMeErrors,
  PatchApiV1UsersMePasswordData,
  PatchApiV1UsersMePasswordErrors,
  PatchApiV1UsersMePasswordResponses,
  PatchApiV1UsersMeResponses,
  PostApiV1ItemsData,
  PostApiV1ItemsErrors,
  PostApiV1ItemsResponses,
  PostApiV1LoginAccessTokenData,
  PostApiV1LoginAccessTokenErrors,
  PostApiV1LoginAccessTokenResponses,
  PostApiV1LoginTestTokenData,
  PostApiV1LoginTestTokenErrors,
  PostApiV1LoginTestTokenResponses,
  PostApiV1PasswordRecoveryData,
  PostApiV1PasswordRecoveryErrors,
  PostApiV1PasswordRecoveryHtmlContentByEmailData,
  PostApiV1PasswordRecoveryHtmlContentByEmailErrors,
  PostApiV1PasswordRecoveryHtmlContentByEmailResponses,
  PostApiV1PasswordRecoveryResponses,
  PostApiV1ResetPasswordData,
  PostApiV1ResetPasswordErrors,
  PostApiV1ResetPasswordResponses,
  PostApiV1UsersData,
  PostApiV1UsersErrors,
  PostApiV1UsersResponses,
  PostApiV1UsersSignupData,
  PostApiV1UsersSignupErrors,
  PostApiV1UsersSignupResponses,
  PostApiV1UtilsTestEmailData,
  PostApiV1UtilsTestEmailErrors,
  PostApiV1UtilsTestEmailResponses,
  PutApiV1ItemsByIdData,
  PutApiV1ItemsByIdErrors,
  PutApiV1ItemsByIdResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

export class LoginService {
  /**
   * Login for access token
   *
   * OAuth2-compatible token login endpoint.
   *
   * Authenticates a user with email and password, returning a JWT access token
   * for authenticating subsequent API requests.
   *
   * **Authentication:**
   * This endpoint follows the OAuth2 password flow. The `username` field should
   * contain the user's email address.
   *
   * **Rate Limiting:**
   * Limited to 5 requests per minute to prevent brute-force attacks.
   *
   * **Token Usage:**
   * Include the returned token in the `Authorization` header of subsequent requests:
   * ```
   * Authorization: Bearer <access_token>
   * ```
   */
  public static loginAccessToken<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1LoginAccessTokenData, ThrowOnError>,
  ): RequestResult<
    PostApiV1LoginAccessTokenResponses,
    PostApiV1LoginAccessTokenErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1LoginAccessTokenResponses,
      PostApiV1LoginAccessTokenErrors,
      ThrowOnError,
      "data"
    >({
      ...urlSearchParamsBodySerializer,
      responseStyle: "data",
      url: "/api/v1/login/access-token",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    })
  }

  /**
   * Test access token
   *
   * Validate an access token and return the current user's information.
   *
   * **Use Cases:**
   * - Verify token is still valid and not expired
   * - Retrieve current user profile data
   * - Check authentication status in frontend applications
   *
   * **Authentication Required:**
   * Include the JWT token in the Authorization header.
   */
  public static testToken<ThrowOnError extends boolean = true>(
    options?: Options<PostApiV1LoginTestTokenData, ThrowOnError>,
  ): RequestResult<
    PostApiV1LoginTestTokenResponses,
    PostApiV1LoginTestTokenErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).post<
      PostApiV1LoginTestTokenResponses,
      PostApiV1LoginTestTokenErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/login/test-token",
      ...options,
    })
  }

  /**
   * Request password recovery
   *
   * Initiate password recovery by sending a reset link to the user's email.
   *
   * **Process:**
   * 1. User provides their registered email address in the JSON request body
   * 2. System generates a time-limited password reset token (valid for 24 hours)
   * 3. An email with reset instructions is sent to the user
   * 4. User clicks the link and is directed to the password reset form
   *
   * **Rate Limiting:**
   * Limited to 5 requests per minute to prevent abuse.
   *
   * **Security Notes:**
   * - The reset token is a JWT with a short expiration time
   * - Always returns a generic success response to prevent account enumeration
   */
  public static recoverPassword<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1PasswordRecoveryData, ThrowOnError>,
  ): RequestResult<
    PostApiV1PasswordRecoveryResponses,
    PostApiV1PasswordRecoveryErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1PasswordRecoveryResponses,
      PostApiV1PasswordRecoveryErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/password-recovery",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Reset password
   *
   * Reset a user's password using a valid reset token.
   *
   * **Requirements:**
   * - A valid, non-expired password reset token (obtained via password recovery email)
   * - New password must be 8-128 characters long
   *
   * **Process:**
   * 1. User receives password recovery email with reset link
   * 2. Link contains a JWT token that identifies the user
   * 3. User submits the token along with their new password
   * 4. System validates the token, updates the password, and returns success
   *
   * **Rate Limiting:**
   * Limited to 5 requests per minute.
   *
   * **Security Notes:**
   * - Tokens are single-use and expire after 24 hours
   * - Old password is not required (user may have forgotten it)
   * - Password is hashed with Argon2id before storage
   */
  public static resetPassword<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1ResetPasswordData, ThrowOnError>,
  ): RequestResult<
    PostApiV1ResetPasswordResponses,
    PostApiV1ResetPasswordErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1ResetPasswordResponses,
      PostApiV1ResetPasswordErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/reset-password/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Preview password recovery email
   *
   * Generate and preview the HTML content of a password recovery email.
   *
   * **Superuser Only:**
   * This endpoint is restricted to superusers for administrative purposes.
   *
   * **Use Cases:**
   * - Preview email templates during development
   * - Debug email rendering issues
   * - Generate manual password reset links for users
   *
   * **Response:**
   * Returns the rendered HTML email content with the subject in a response header.
   */
  public static recoverPasswordHtmlContent<ThrowOnError extends boolean = true>(
    options: Options<
      PostApiV1PasswordRecoveryHtmlContentByEmailData,
      ThrowOnError
    >,
  ): RequestResult<
    PostApiV1PasswordRecoveryHtmlContentByEmailResponses,
    PostApiV1PasswordRecoveryHtmlContentByEmailErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1PasswordRecoveryHtmlContentByEmailResponses,
      PostApiV1PasswordRecoveryHtmlContentByEmailErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/password-recovery-html-content/{email}",
      ...options,
    })
  }
}

export class UsersService {
  /**
   * List users (Admin)
   *
   * Retrieve a paginated list of all users in the system.
   *
   * **Access:** Superuser only
   *
   * Returns user data without sensitive fields (password hashes).
   */
  public static readUsers<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1UsersData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UsersResponses,
    GetApiV1UsersErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1UsersResponses,
      GetApiV1UsersErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/",
      ...options,
    })
  }

  /**
   * Create user (Admin)
   *
   * Create a new user account with full control over all fields.
   *
   * **Access:** Superuser only
   *
   * Allows setting:
   * - Email and password
   * - Full name
   * - Active status
   * - Superuser privileges
   *
   * If email sending is enabled, sends a secure onboarding email with a
   * password setup link.
   */
  public static createUser<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1UsersData, ThrowOnError>,
  ): RequestResult<
    PostApiV1UsersResponses,
    PostApiV1UsersErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1UsersResponses,
      PostApiV1UsersErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Delete current user account
   *
   * Permanently delete the current user's account.
   *
   * **Warning:** This action cannot be undone. All associated data will be deleted.
   *
   * **Restriction:** Superusers cannot delete themselves through this endpoint
   * to prevent accidental loss of admin access.
   */
  public static deleteUserMe<ThrowOnError extends boolean = true>(
    options?: Options<DeleteApiV1UsersMeData, ThrowOnError>,
  ): RequestResult<
    DeleteApiV1UsersMeResponses,
    DeleteApiV1UsersMeErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).delete<
      DeleteApiV1UsersMeResponses,
      DeleteApiV1UsersMeErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    })
  }

  /**
   * Get current user profile
   *
   * Retrieve the profile information for the currently authenticated user.
   *
   * Returns user data without sensitive fields (password hash).
   */
  public static readUserMe<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1UsersMeData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UsersMeResponses,
    GetApiV1UsersMeErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1UsersMeResponses,
      GetApiV1UsersMeErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    })
  }

  /**
   * Update current user profile
   *
   * Update the current authenticated user's profile information.
   *
   * **Updatable fields:**
   * - email (must be unique)
   * - full_name
   *
   * **Note:** To change password, use the `/me/password` endpoint.
   */
  public static updateUserMe<ThrowOnError extends boolean = true>(
    options: Options<PatchApiV1UsersMeData, ThrowOnError>,
  ): RequestResult<
    PatchApiV1UsersMeResponses,
    PatchApiV1UsersMeErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).patch<
      PatchApiV1UsersMeResponses,
      PatchApiV1UsersMeErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Change current user password
   *
   * Change the password for the current authenticated user.
   *
   * **Requirements:**
   * - Must provide current password for verification
   * - New password must be different from current password
   * - Password must meet minimum requirements (8+ characters)
   */
  public static updatePasswordMe<ThrowOnError extends boolean = true>(
    options: Options<PatchApiV1UsersMePasswordData, ThrowOnError>,
  ): RequestResult<
    PatchApiV1UsersMePasswordResponses,
    PatchApiV1UsersMePasswordErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).patch<
      PatchApiV1UsersMePasswordResponses,
      PatchApiV1UsersMePasswordErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me/password",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Register new user (Public)
   *
   * Public registration endpoint for new user self-signup.
   *
   * **Rate Limited:** This endpoint is rate-limited to prevent abuse.
   *
   * **No Authentication Required:** This is a public endpoint.
   *
   * New users are created with:
   * - `is_active = True`
   * - `is_superuser = False`
   */
  public static registerUser<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1UsersSignupData, ThrowOnError>,
  ): RequestResult<
    PostApiV1UsersSignupResponses,
    PostApiV1UsersSignupErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1UsersSignupResponses,
      PostApiV1UsersSignupErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/users/signup",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Delete user (Admin)
   *
   * Permanently delete a user and all their associated data.
   *
   * **Access:** Superuser only
   *
   * **Warning:** This action cannot be undone. All user's items will also be deleted.
   *
   * **Restriction:** Superusers cannot delete themselves through this endpoint.
   */
  public static deleteUser<ThrowOnError extends boolean = true>(
    options: Options<DeleteApiV1UsersByUserIdData, ThrowOnError>,
  ): RequestResult<
    DeleteApiV1UsersByUserIdResponses,
    DeleteApiV1UsersByUserIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).delete<
      DeleteApiV1UsersByUserIdResponses,
      DeleteApiV1UsersByUserIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    })
  }

  /**
   * Get user by ID
   *
   * Retrieve a specific user by their unique identifier.
   *
   * **Access Control:**
   * - Regular users: Can only retrieve their own profile
   * - Superusers: Can retrieve any user
   */
  public static readUserById<ThrowOnError extends boolean = true>(
    options: Options<GetApiV1UsersByUserIdData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UsersByUserIdResponses,
    GetApiV1UsersByUserIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).get<
      GetApiV1UsersByUserIdResponses,
      GetApiV1UsersByUserIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    })
  }

  /**
   * Update user (Admin)
   *
   * Update any user's information by their ID.
   *
   * **Access:** Superuser only
   *
   * **Updatable fields:**
   * - email (must be unique)
   * - full_name
   * - password
   * - is_active
   * - is_superuser
   */
  public static updateUser<ThrowOnError extends boolean = true>(
    options: Options<PatchApiV1UsersByUserIdData, ThrowOnError>,
  ): RequestResult<
    PatchApiV1UsersByUserIdResponses,
    PatchApiV1UsersByUserIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).patch<
      PatchApiV1UsersByUserIdResponses,
      PatchApiV1UsersByUserIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   *
   * Test emails.
   */
  public static testEmail<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1UtilsTestEmailData, ThrowOnError>,
  ): RequestResult<
    PostApiV1UtilsTestEmailResponses,
    PostApiV1UtilsTestEmailErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1UtilsTestEmailResponses,
      PostApiV1UtilsTestEmailErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/utils/test-email/",
      ...options,
    })
  }

  /**
   * Health Check
   *
   * Legacy health check for backwards compatibility.
   */
  public static healthCheck<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1UtilsHealthCheckData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UtilsHealthCheckResponses,
    unknown,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1UtilsHealthCheckResponses,
      unknown,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/utils/health-check/",
      ...options,
    })
  }

  /**
   * Health
   *
   * Production health check with database connectivity verification.
   *
   * Uses a short-lived raw connection instead of a pooled session to avoid
   * exhausting the connection pool under heavy monitoring (resolves M-6).
   */
  public static health<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1UtilsHealthData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UtilsHealthResponses,
    unknown,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1UtilsHealthResponses,
      unknown,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/utils/health/",
      ...options,
    })
  }
}

export class ItemsService {
  /**
   * List items
   *
   * Retrieve a paginated list of items with optional filtering.
   *
   * **Access Control:**
   * - Regular users: Returns only items owned by the current user
   * - Superusers: Returns all items in the system
   *
   * **Pagination:**
   * - Use `skip` and `limit` parameters for pagination
   * - Maximum limit is 100 items per request
   *
   * **Filtering:**
   * - Filter by `content_type` to get items of a specific type
   */
  public static readItems<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1ItemsData, ThrowOnError>,
  ): RequestResult<
    GetApiV1ItemsResponses,
    GetApiV1ItemsErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1ItemsResponses,
      GetApiV1ItemsErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/",
      ...options,
    })
  }

  /**
   * Create item
   *
   * Create a new item owned by the current user.
   *
   * The item will be automatically assigned to the authenticated user.
   * All items have a `content_type` that defaults to "general".
   */
  public static createItem<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1ItemsData, ThrowOnError>,
  ): RequestResult<
    PostApiV1ItemsResponses,
    PostApiV1ItemsErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1ItemsResponses,
      PostApiV1ItemsErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Delete item
   *
   * Permanently delete an item by ID.
   *
   * **Warning:** This action cannot be undone.
   *
   * **Access Control:**
   * - Regular users: Can only delete items they own
   * - Superusers: Can delete any item
   */
  public static deleteItem<ThrowOnError extends boolean = true>(
    options: Options<DeleteApiV1ItemsByIdData, ThrowOnError>,
  ): RequestResult<
    DeleteApiV1ItemsByIdResponses,
    DeleteApiV1ItemsByIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).delete<
      DeleteApiV1ItemsByIdResponses,
      DeleteApiV1ItemsByIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
    })
  }

  /**
   * Get item by ID
   *
   * Retrieve a single item by its unique identifier.
   *
   * **Access Control:**
   * - Regular users: Can only retrieve items they own
   * - Superusers: Can retrieve any item
   */
  public static readItem<ThrowOnError extends boolean = true>(
    options: Options<GetApiV1ItemsByIdData, ThrowOnError>,
  ): RequestResult<
    GetApiV1ItemsByIdResponses,
    GetApiV1ItemsByIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).get<
      GetApiV1ItemsByIdResponses,
      GetApiV1ItemsByIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
    })
  }

  /**
   * Update item
   *
   * Update an existing item by ID.
   *
   * **Partial Updates:**
   * Only fields included in the request body will be updated.
   * Omitted fields retain their current values.
   *
   * **Access Control:**
   * - Regular users: Can only update items they own
   * - Superusers: Can update any item
   */
  public static updateItem<ThrowOnError extends boolean = true>(
    options: Options<PutApiV1ItemsByIdData, ThrowOnError>,
  ): RequestResult<
    PutApiV1ItemsByIdResponses,
    PutApiV1ItemsByIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).put<
      PutApiV1ItemsByIdResponses,
      PutApiV1ItemsByIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/items/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }
}
