// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client"
import { client } from "./client.gen"
import type {
  DeleteApiV1UsersByUserIdData,
  DeleteApiV1UsersByUserIdErrors,
  DeleteApiV1UsersByUserIdResponses,
  DeleteApiV1UsersMeData,
  DeleteApiV1UsersMeErrors,
  DeleteApiV1UsersMeResponses,
  GetApiV1JobsByJobIdArtifactsByArtifactIdData,
  GetApiV1JobsByJobIdArtifactsByArtifactIdErrors,
  GetApiV1JobsByJobIdArtifactsByArtifactIdResponses,
  GetApiV1JobsByJobIdArtifactsData,
  GetApiV1JobsByJobIdArtifactsErrors,
  GetApiV1JobsByJobIdArtifactsResponses,
  GetApiV1JobsByJobIdData,
  GetApiV1JobsByJobIdErrors,
  GetApiV1JobsByJobIdResponses,
  GetApiV1JobsData,
  GetApiV1JobsErrors,
  GetApiV1JobsResponses,
  GetApiV1SystemAuthStatusData,
  GetApiV1SystemAuthStatusResponses,
  GetApiV1SystemReadinessData,
  GetApiV1SystemReadinessResponses,
  GetApiV1UsersByUserIdData,
  GetApiV1UsersByUserIdErrors,
  GetApiV1UsersByUserIdResponses,
  GetApiV1UsersData,
  GetApiV1UsersErrors,
  GetApiV1UsersMeData,
  GetApiV1UsersMeErrors,
  GetApiV1UsersMeResponses,
  GetApiV1UsersResponses,
  GetApiV1UtilsHealthCheckData,
  GetApiV1UtilsHealthCheckResponses,
  GetApiV1UtilsHealthData,
  GetApiV1UtilsHealthResponses,
  PatchApiV1UsersByUserIdData,
  PatchApiV1UsersByUserIdErrors,
  PatchApiV1UsersByUserIdResponses,
  PatchApiV1UsersMeData,
  PatchApiV1UsersMeErrors,
  PatchApiV1UsersMePasswordData,
  PatchApiV1UsersMePasswordErrors,
  PatchApiV1UsersMePasswordResponses,
  PatchApiV1UsersMeResponses,
  PostApiV1JobsData,
  PostApiV1JobsErrors,
  PostApiV1JobsResponses,
  PostApiV1JobsUploadData,
  PostApiV1JobsUploadErrors,
  PostApiV1JobsUploadResponses,
  PostApiV1LoginAccessTokenData,
  PostApiV1LoginAccessTokenErrors,
  PostApiV1LoginAccessTokenResponses,
  PostApiV1LoginTestTokenData,
  PostApiV1LoginTestTokenErrors,
  PostApiV1LoginTestTokenResponses,
  PostApiV1PasswordRecoveryData,
  PostApiV1PasswordRecoveryErrors,
  PostApiV1PasswordRecoveryHtmlContentByEmailData,
  PostApiV1PasswordRecoveryHtmlContentByEmailErrors,
  PostApiV1PasswordRecoveryHtmlContentByEmailResponses,
  PostApiV1PasswordRecoveryResponses,
  PostApiV1ResetPasswordData,
  PostApiV1ResetPasswordErrors,
  PostApiV1ResetPasswordResponses,
  PostApiV1SystemAuthStartData,
  PostApiV1SystemAuthStartResponses,
  PostApiV1UsersData,
  PostApiV1UsersErrors,
  PostApiV1UsersResponses,
  PostApiV1UsersSignupData,
  PostApiV1UsersSignupErrors,
  PostApiV1UsersSignupResponses,
  PostApiV1UtilsTestEmailData,
  PostApiV1UtilsTestEmailErrors,
  PostApiV1UtilsTestEmailResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

export class LoginService {
  /**
   * Login for access token
   *
   * OAuth2-compatible token login endpoint.
   *
   * Authenticates a user with email and password, returning a JWT access token
   * for authenticating subsequent API requests.
   *
   * **Authentication:**
   * This endpoint follows the OAuth2 password flow. The `username` field should
   * contain the user's email address.
   *
   * **Rate Limiting:**
   * Limited to 5 requests per minute to prevent brute-force attacks.
   *
   * **Token Usage:**
   * Include the returned token in the `Authorization` header of subsequent requests:
   * ```
   * Authorization: Bearer <access_token>
   * ```
   */
  public static loginAccessToken<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1LoginAccessTokenData, ThrowOnError>,
  ): RequestResult<
    PostApiV1LoginAccessTokenResponses,
    PostApiV1LoginAccessTokenErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1LoginAccessTokenResponses,
      PostApiV1LoginAccessTokenErrors,
      ThrowOnError,
      "data"
    >({
      ...urlSearchParamsBodySerializer,
      responseStyle: "data",
      url: "/api/v1/login/access-token",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    })
  }

  /**
   * Test access token
   *
   * Validate an access token and return the current user's information.
   *
   * **Use Cases:**
   * - Verify token is still valid and not expired
   * - Retrieve current user profile data
   * - Check authentication status in frontend applications
   *
   * **Authentication Required:**
   * Include the JWT token in the Authorization header.
   */
  public static testToken<ThrowOnError extends boolean = true>(
    options?: Options<PostApiV1LoginTestTokenData, ThrowOnError>,
  ): RequestResult<
    PostApiV1LoginTestTokenResponses,
    PostApiV1LoginTestTokenErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).post<
      PostApiV1LoginTestTokenResponses,
      PostApiV1LoginTestTokenErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/login/test-token",
      ...options,
    })
  }

  /**
   * Request password recovery
   *
   * Initiate password recovery by sending a reset link to the user's email.
   *
   * **Process:**
   * 1. User provides their registered email address in the JSON request body
   * 2. System generates a time-limited password reset token (valid for 24 hours)
   * 3. An email with reset instructions is sent to the user
   * 4. User clicks the link and is directed to the password reset form
   *
   * **Rate Limiting:**
   * Limited to 5 requests per minute to prevent abuse.
   *
   * **Security Notes:**
   * - The reset token is a JWT with a short expiration time
   * - Always returns a generic success response to prevent account enumeration
   */
  public static recoverPassword<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1PasswordRecoveryData, ThrowOnError>,
  ): RequestResult<
    PostApiV1PasswordRecoveryResponses,
    PostApiV1PasswordRecoveryErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1PasswordRecoveryResponses,
      PostApiV1PasswordRecoveryErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/password-recovery",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Reset password
   *
   * Reset a user's password using a valid reset token.
   *
   * **Requirements:**
   * - A valid, non-expired password reset token (obtained via password recovery email)
   * - New password must be 8-128 characters long
   *
   * **Process:**
   * 1. User receives password recovery email with reset link
   * 2. Link contains a JWT token that identifies the user
   * 3. User submits the token along with their new password
   * 4. System validates the token, updates the password, and returns success
   *
   * **Rate Limiting:**
   * Limited to 5 requests per minute.
   *
   * **Security Notes:**
   * - Tokens are single-use and expire after 24 hours
   * - Old password is not required (user may have forgotten it)
   * - Password is hashed with Argon2id before storage
   */
  public static resetPassword<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1ResetPasswordData, ThrowOnError>,
  ): RequestResult<
    PostApiV1ResetPasswordResponses,
    PostApiV1ResetPasswordErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1ResetPasswordResponses,
      PostApiV1ResetPasswordErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/reset-password/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Preview password recovery email
   *
   * Generate and preview the HTML content of a password recovery email.
   *
   * **Superuser Only:**
   * This endpoint is restricted to superusers for administrative purposes.
   *
   * **Use Cases:**
   * - Preview email templates during development
   * - Debug email rendering issues
   * - Generate manual password reset links for users
   *
   * **Response:**
   * Returns the rendered HTML email content with the subject in a response header.
   */
  public static recoverPasswordHtmlContent<ThrowOnError extends boolean = true>(
    options: Options<
      PostApiV1PasswordRecoveryHtmlContentByEmailData,
      ThrowOnError
    >,
  ): RequestResult<
    PostApiV1PasswordRecoveryHtmlContentByEmailResponses,
    PostApiV1PasswordRecoveryHtmlContentByEmailErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1PasswordRecoveryHtmlContentByEmailResponses,
      PostApiV1PasswordRecoveryHtmlContentByEmailErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/password-recovery-html-content/{email}",
      ...options,
    })
  }
}

export class UsersService {
  /**
   * List users (Admin)
   *
   * Retrieve a paginated list of all users in the system.
   *
   * **Access:** Superuser only
   *
   * Returns user data without sensitive fields (password hashes).
   */
  public static readUsers<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1UsersData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UsersResponses,
    GetApiV1UsersErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1UsersResponses,
      GetApiV1UsersErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/",
      ...options,
    })
  }

  /**
   * Create user (Admin)
   *
   * Create a new user account with full control over all fields.
   *
   * **Access:** Superuser only
   *
   * Allows setting:
   * - Email and password
   * - Full name
   * - Active status
   * - Superuser privileges
   *
   * If email sending is enabled, sends a secure onboarding email with a
   * password setup link.
   */
  public static createUser<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1UsersData, ThrowOnError>,
  ): RequestResult<
    PostApiV1UsersResponses,
    PostApiV1UsersErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1UsersResponses,
      PostApiV1UsersErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Delete current user account
   *
   * Permanently delete the current user's account.
   *
   * **Warning:** This action cannot be undone. Engine-owned course requests,
   * checkpoints, delivery records, and artifacts are purged before the account.
   * This operation does not erase retained logs or backup copies; their retention
   * is handled separately.
   *
   * **Failure behavior:** A purge failure leaves the account intact. If engine
   * purge succeeds but PostgreSQL deletion fails, retrying is safe.
   *
   * **Restriction:** Superusers cannot delete themselves through this endpoint
   * to prevent accidental loss of admin access.
   */
  public static deleteUserMe<ThrowOnError extends boolean = true>(
    options?: Options<DeleteApiV1UsersMeData, ThrowOnError>,
  ): RequestResult<
    DeleteApiV1UsersMeResponses,
    DeleteApiV1UsersMeErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).delete<
      DeleteApiV1UsersMeResponses,
      DeleteApiV1UsersMeErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    })
  }

  /**
   * Get current user profile
   *
   * Retrieve the profile information for the currently authenticated user.
   *
   * Returns user data without sensitive fields (password hash).
   */
  public static readUserMe<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1UsersMeData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UsersMeResponses,
    GetApiV1UsersMeErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1UsersMeResponses,
      GetApiV1UsersMeErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    })
  }

  /**
   * Update current user profile
   *
   * Update the current authenticated user's profile information.
   *
   * **Updatable fields:**
   * - email (must be unique)
   * - full_name
   *
   * **Note:** To change password, use the `/me/password` endpoint.
   */
  public static updateUserMe<ThrowOnError extends boolean = true>(
    options: Options<PatchApiV1UsersMeData, ThrowOnError>,
  ): RequestResult<
    PatchApiV1UsersMeResponses,
    PatchApiV1UsersMeErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).patch<
      PatchApiV1UsersMeResponses,
      PatchApiV1UsersMeErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Change current user password
   *
   * Change the password for the current authenticated user.
   *
   * **Requirements:**
   * - Must provide current password for verification
   * - New password must be different from current password
   * - Password must meet minimum requirements (8+ characters)
   */
  public static updatePasswordMe<ThrowOnError extends boolean = true>(
    options: Options<PatchApiV1UsersMePasswordData, ThrowOnError>,
  ): RequestResult<
    PatchApiV1UsersMePasswordResponses,
    PatchApiV1UsersMePasswordErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).patch<
      PatchApiV1UsersMePasswordResponses,
      PatchApiV1UsersMePasswordErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me/password",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Register new user (Local opt-in)
   *
   * Conditional registration endpoint for new user self-signup.
   *
   * **Rate Limited:** This endpoint is rate-limited to prevent abuse.
   *
   * **Local Opt-in:** No authentication is required only when
   * `ENVIRONMENT=local` and `ENABLE_PUBLIC_SIGNUP=true`. Signup is disabled by
   * default and cannot be enabled in staging or production.
   *
   * New users are created with:
   * - `is_active = True`
   * - `is_superuser = False`
   */
  public static registerUser<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1UsersSignupData, ThrowOnError>,
  ): RequestResult<
    PostApiV1UsersSignupResponses,
    PostApiV1UsersSignupErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1UsersSignupResponses,
      PostApiV1UsersSignupErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/users/signup",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Delete user (Admin)
   *
   * Permanently delete a user's live account and engine-owned course state.
   *
   * **Access:** Superuser only
   *
   * **Warning:** This action cannot be undone. Engine-owned course requests,
   * checkpoints, delivery records, and artifacts are purged before the account.
   * This operation does not erase retained logs or backup copies; their retention
   * is handled separately.
   *
   * **Failure behavior:** A purge failure leaves the account intact. If engine
   * purge succeeds but PostgreSQL deletion fails, retrying is safe.
   *
   * **Restriction:** Superusers cannot delete themselves through this endpoint.
   */
  public static deleteUser<ThrowOnError extends boolean = true>(
    options: Options<DeleteApiV1UsersByUserIdData, ThrowOnError>,
  ): RequestResult<
    DeleteApiV1UsersByUserIdResponses,
    DeleteApiV1UsersByUserIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).delete<
      DeleteApiV1UsersByUserIdResponses,
      DeleteApiV1UsersByUserIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    })
  }

  /**
   * Get user by ID
   *
   * Retrieve a specific user by their unique identifier.
   *
   * **Access Control:**
   * - Regular users: Can only retrieve their own profile
   * - Superusers: Can retrieve any user
   */
  public static readUserById<ThrowOnError extends boolean = true>(
    options: Options<GetApiV1UsersByUserIdData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UsersByUserIdResponses,
    GetApiV1UsersByUserIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).get<
      GetApiV1UsersByUserIdResponses,
      GetApiV1UsersByUserIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    })
  }

  /**
   * Update user (Admin)
   *
   * Update any user's information by their ID.
   *
   * **Access:** Superuser only
   *
   * **Updatable fields:**
   * - email (must be unique)
   * - full_name
   * - password
   * - is_active
   * - is_superuser
   */
  public static updateUser<ThrowOnError extends boolean = true>(
    options: Options<PatchApiV1UsersByUserIdData, ThrowOnError>,
  ): RequestResult<
    PatchApiV1UsersByUserIdResponses,
    PatchApiV1UsersByUserIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).patch<
      PatchApiV1UsersByUserIdResponses,
      PatchApiV1UsersByUserIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   *
   * Test emails.
   */
  public static testEmail<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1UtilsTestEmailData, ThrowOnError>,
  ): RequestResult<
    PostApiV1UtilsTestEmailResponses,
    PostApiV1UtilsTestEmailErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1UtilsTestEmailResponses,
      PostApiV1UtilsTestEmailErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/utils/test-email/",
      ...options,
    })
  }

  /**
   * Health Check
   *
   * Legacy health check for backwards compatibility.
   */
  public static healthCheck<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1UtilsHealthCheckData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UtilsHealthCheckResponses,
    unknown,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1UtilsHealthCheckResponses,
      unknown,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/utils/health-check/",
      ...options,
    })
  }

  /**
   * Health
   *
   * Production health check with database connectivity verification.
   *
   * Uses a short-lived raw connection instead of a pooled session to avoid
   * exhausting the connection pool under heavy monitoring (resolves M-6).
   */
  public static health<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1UtilsHealthData, ThrowOnError>,
  ): RequestResult<
    GetApiV1UtilsHealthResponses,
    unknown,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1UtilsHealthResponses,
      unknown,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      url: "/api/v1/utils/health/",
      ...options,
    })
  }
}

export class JobsService {
  /**
   * List retained course jobs
   *
   * Returns one stable newest-first owner page. The opaque continuation can be replayed to recover older retained jobs without exposing engine persistence details.
   */
  public static listJobs<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1JobsData, ThrowOnError>,
  ): RequestResult<
    GetApiV1JobsResponses,
    GetApiV1JobsErrors,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1JobsResponses,
      GetApiV1JobsErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/jobs",
      ...options,
    })
  }

  /**
   * Submit a text or URL course job
   *
   * Validates one prompt, pasted text, URL, or YouTube intent and returns only after package policy, admission, and durable commit succeed.
   */
  public static submitJob<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1JobsData, ThrowOnError>,
  ): RequestResult<
    PostApiV1JobsResponses,
    PostApiV1JobsErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1JobsResponses,
      PostApiV1JobsErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/jobs",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Submit a document course job
   *
   * Accepts exactly one strict metadata object and one bounded PDF, DOCX, or PPTX file, then returns only after durable package commit.
   */
  public static submitJobUpload<ThrowOnError extends boolean = true>(
    options: Options<PostApiV1JobsUploadData, ThrowOnError>,
  ): RequestResult<
    PostApiV1JobsUploadResponses,
    PostApiV1JobsUploadErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).post<
      PostApiV1JobsUploadResponses,
      PostApiV1JobsUploadErrors,
      ThrowOnError,
      "data"
    >({
      ...formDataBodySerializer,
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/jobs/upload",
      ...options,
      headers: {
        "Content-Type": null,
        ...options.headers,
      },
    })
  }

  /**
   * Read current course job status and result
   *
   * Returns one revisioned owner-scoped allowlist. Responses are private and non-cacheable; P0 does not implement conditional cache validators.
   */
  public static readJob<ThrowOnError extends boolean = true>(
    options: Options<GetApiV1JobsByJobIdData, ThrowOnError>,
  ): RequestResult<
    GetApiV1JobsByJobIdResponses,
    GetApiV1JobsByJobIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).get<
      GetApiV1JobsByJobIdResponses,
      GetApiV1JobsByJobIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/jobs/{job_id}",
      ...options,
    })
  }

  /**
   * Read the verified course artifact manifest
   *
   * Returns owner-scoped path-free metadata grouped by educational deliverable after package integrity verification.
   */
  public static readJobArtifacts<ThrowOnError extends boolean = true>(
    options: Options<GetApiV1JobsByJobIdArtifactsData, ThrowOnError>,
  ): RequestResult<
    GetApiV1JobsByJobIdArtifactsResponses,
    GetApiV1JobsByJobIdArtifactsErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).get<
      GetApiV1JobsByJobIdArtifactsResponses,
      GetApiV1JobsByJobIdArtifactsErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/jobs/{job_id}/artifacts",
      ...options,
    })
  }

  /**
   * Download one verified course artifact
   *
   * Reauthorizes and verifies one canonical artifact before headers, then streams its existing private descriptor without buffering.
   */
  public static downloadJobArtifact<ThrowOnError extends boolean = true>(
    options: Options<
      GetApiV1JobsByJobIdArtifactsByArtifactIdData,
      ThrowOnError
    >,
  ): RequestResult<
    GetApiV1JobsByJobIdArtifactsByArtifactIdResponses,
    GetApiV1JobsByJobIdArtifactsByArtifactIdErrors,
    ThrowOnError,
    "data"
  > {
    return (options.client ?? client).get<
      GetApiV1JobsByJobIdArtifactsByArtifactIdResponses,
      GetApiV1JobsByJobIdArtifactsByArtifactIdErrors,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/jobs/{job_id}/artifacts/{artifact_id}",
      ...options,
    })
  }
}

export class SystemService {
  /**
   * Read cached course-system readiness
   *
   * Returns the latest coarse cached system projection. This endpoint never starts Codex, MCP, provider, database, or artifact probe work.
   */
  public static readSystemReadiness<ThrowOnError extends boolean = true>(
    options?: Options<GetApiV1SystemReadinessData, ThrowOnError>,
  ): RequestResult<
    GetApiV1SystemReadinessResponses,
    unknown,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1SystemReadinessResponses,
      unknown,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/system/readiness",
      ...options,
    })
  }

  /**
   * Start dedicated ChatGPT device authentication
   *
   * Superuser-only. Returns only the validated OpenAI verification URL, short user code, safe state, and recovery message.
   */
  public static startSystemAuthentication<ThrowOnError extends boolean = true>(
    options?: Options<PostApiV1SystemAuthStartData, ThrowOnError>,
  ): RequestResult<
    PostApiV1SystemAuthStartResponses,
    unknown,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).post<
      PostApiV1SystemAuthStartResponses,
      unknown,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/system/auth/start",
      ...options,
    })
  }

  /**
   * Read cached dedicated ChatGPT authentication status
   *
   * Superuser-only. Reads a shell cache and never refreshes credentials or starts a second provider runtime.
   */
  public static readSystemAuthenticationStatus<
    ThrowOnError extends boolean = true,
  >(
    options?: Options<GetApiV1SystemAuthStatusData, ThrowOnError>,
  ): RequestResult<
    GetApiV1SystemAuthStatusResponses,
    unknown,
    ThrowOnError,
    "data"
  > {
    return (options?.client ?? client).get<
      GetApiV1SystemAuthStatusResponses,
      unknown,
      ThrowOnError,
      "data"
    >({
      responseStyle: "data",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/system/auth/status",
      ...options,
    })
  }
}
