// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * ArtifactDeliverable
 *
 * Canonical educational products generated for one accepted course.
 */
export type ArtifactDeliverable =
  | "course"
  | "review_pack"
  | "assessment"
  | "answer_key"

/**
 * ArtifactDeliverableGroupPublic
 *
 * One educational deliverable with at most four canonical formats.
 */
export type ArtifactDeliverableGroupPublic = {
  deliverable: ArtifactDeliverable
  /**
   * Artifacts
   */
  artifacts: Array<ArtifactMetadataPublic>
}

/**
 * ArtifactFormat
 *
 * Portable output formats emitted by the deterministic renderer.
 */
export type ArtifactFormat = "html" | "markdown" | "pdf" | "docx"

/**
 * ArtifactManifestPublic
 *
 * Verified canonical metadata grouped as four educational products.
 */
export type ArtifactManifestPublic = {
  /**
   * Schema Version
   */
  schema_version: "1.0"
  /**
   * Job Id
   */
  job_id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Deliverables
   */
  deliverables: Array<ArtifactDeliverableGroupPublic>
}

/**
 * ArtifactMetadataPublic
 *
 * Path-free metadata and stable download URL for one rendered artifact.
 */
export type ArtifactMetadataPublic = {
  /**
   * Artifact Id
   */
  artifact_id: string
  format: ArtifactFormat
  /**
   * File Name
   */
  file_name: string
  /**
   * Media Type
   */
  media_type: string
  /**
   * Size Bytes
   */
  size_bytes: number
  /**
   * Content Hash
   */
  content_hash: string
  /**
   * Download Url
   */
  download_url: string
}

/**
 * Body_jobs-submit_job_upload
 */
export type BodyJobsSubmitJobUpload = {
  /**
   * Metadata
   *
   * Strict JSON course preferences, consent, and age group.
   */
  metadata: string
  /**
   * File
   *
   * One bounded PDF, DOCX, or PPTX source.
   */
  file: Blob | File
}

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
  /**
   * Grant Type
   */
  grant_type?: string | null
  /**
   * Username
   */
  username: string
  /**
   * Password
   */
  password: string
  /**
   * Scope
   */
  scope?: string
  /**
   * Client Id
   */
  client_id?: string | null
  /**
   * Client Secret
   */
  client_secret?: string | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * HealthCheckResponse
 */
export type HealthCheckResponse = {
  /**
   * Status
   */
  status: string
  /**
   * Timestamp
   */
  timestamp: string
  /**
   * Database
   */
  database: string
  /**
   * Version
   */
  version: string
}

/**
 * ItemCreate
 *
 * Request body for creating a new item.
 *
 * Requires title, all other fields are optional. Rejects unknown fields
 * to prevent API misuse.
 */
export type ItemCreate = {
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Source Url
   */
  source_url?: string | null
  /**
   * Content
   */
  content?: string | null
  /**
   * Content Type
   */
  content_type?: "general" | null
  /**
   * Item Metadata
   */
  item_metadata?: {
    [key: string]: unknown
  } | null
}

/**
 * ItemPublic
 */
export type ItemPublic = {
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Source Url
   */
  source_url?: string | null
  /**
   * Content
   */
  content?: string | null
  /**
   * Content Type
   */
  content_type?: "general" | null
  /**
   * Item Metadata
   */
  item_metadata?: {
    [key: string]: unknown
  } | null
  /**
   * Id
   */
  id: string
  /**
   * Owner Id
   */
  owner_id: string
  /**
   * Created At
   */
  created_at?: string | null
}

/**
 * ItemUpdate
 *
 * Request body for updating an item.
 *
 * All fields are optional for partial updates. Rejects unknown fields
 * to prevent API misuse.
 */
export type ItemUpdate = {
  /**
   * Title
   */
  title?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Source Url
   */
  source_url?: string | null
  /**
   * Content
   */
  content?: string | null
  /**
   * Content Type
   */
  content_type?: "general" | null
  /**
   * Item Metadata
   */
  item_metadata?: {
    [key: string]: unknown
  } | null
}

/**
 * ItemsPublic
 */
export type ItemsPublic = {
  /**
   * Data
   */
  data: Array<ItemPublic>
  /**
   * Count
   */
  count: number
}

/**
 * JobAcceptedPublic
 *
 * Allowlisted response returned only after a durable package commit.
 */
export type JobAcceptedPublic = {
  /**
   * Schema Version
   */
  schema_version: "1.0"
  /**
   * Job Id
   */
  job_id: string
  /**
   * Status
   */
  status: "accepted"
  /**
   * Revision
   */
  revision: number
  /**
   * Status Url
   */
  status_url: string
}

/**
 * JobArtifactAvailabilityPublic
 *
 * Link to the verified manifest only after package publication.
 */
export type JobArtifactAvailabilityPublic = {
  /**
   * Available
   */
  available: boolean
  /**
   * Count
   */
  count: number
  /**
   * Manifest Url
   */
  manifest_url: string | null
}

/**
 * JobFailurePublic
 *
 * Reviewed package failure code and fixed safe learner-facing message.
 */
export type JobFailurePublic = {
  code: PublicFailureCode
  /**
   * Message
   */
  message: string
}

/**
 * JobInputPublic
 *
 * Bounded input display metadata without learner-provided source content.
 */
export type JobInputPublic = {
  /**
   * Type
   */
  type:
    | "prompt"
    | "text"
    | "url"
    | "pdf"
    | "document"
    | "slides"
    | "image"
    | "audio"
    | "video"
  /**
   * Display Name
   */
  display_name: string
  /**
   * Size Bytes
   */
  size_bytes: number
  /**
   * Extraction Warnings
   */
  extraction_warnings: Array<string>
  /**
   * Warnings Truncated
   */
  warnings_truncated: boolean
}

/**
 * JobLearnerAgeGroup
 *
 * Privacy-minimized age context passed to package policy.
 */
export type JobLearnerAgeGroup = "minor" | "adult" | "not_provided"

/**
 * JobLearningLevel
 *
 * Reviewed P0 learner-selectable depth intent.
 */
export type JobLearningLevel =
  | "auto"
  | "beginner"
  | "intermediate"
  | "advanced"
  | "mixed"

/**
 * JobPreferences
 *
 * Finite learning intent; all other generation defaults are server-owned.
 */
export type JobPreferences = {
  level: JobLearningLevel
  /**
   * Audience
   */
  audience: string | null
  /**
   * Prior Knowledge
   */
  prior_knowledge: string | null
  /**
   * Learning Goals
   */
  learning_goals: Array<string>
  /**
   * Language
   */
  language: string
}

/**
 * JobProgressPublic
 *
 * Monotonic accepted work with fixed browser-safe explanatory copy.
 */
export type JobProgressPublic = {
  stage: JobProgressStage
  /**
   * Message
   */
  message: string
  /**
   * Completed Units
   */
  completed_units: number
  /**
   * Total Units
   */
  total_units?: number | null
}

/**
 * JobProgressStage
 *
 * Stable browser stages that never reflect a private checkpoint label.
 */
export type JobProgressStage =
  | "queued"
  | "researching"
  | "drafting"
  | "validating"
  | "rendering"
  | "delivering"
  | "ready"
  | "failed"
  | "cancelled"

/**
 * JobResultPublic
 *
 * Coherent bounded result summary once an accepted course plan exists.
 */
export type JobResultPublic = {
  /**
   * Title
   */
  title: string
  /**
   * Audience
   */
  audience: string
  /**
   * Level
   */
  level: "beginner" | "intermediate" | "advanced" | "mixed"
  /**
   * Language
   */
  language: string
  /**
   * Objective Count
   */
  objective_count: number
  /**
   * Module Count
   */
  module_count: number
  /**
   * Sources
   */
  sources: Array<JobSourcePublic>
  /**
   * Sources Truncated
   */
  sources_truncated: boolean
  /**
   * Conflicts
   */
  conflicts: Array<string>
  /**
   * Conflicts Truncated
   */
  conflicts_truncated: boolean
}

/**
 * JobSourcePublic
 *
 * Display-safe bibliographic metadata with no evidence body.
 */
export type JobSourcePublic = {
  /**
   * Title
   */
  title: string
  /**
   * Url
   */
  url: string | null
  /**
   * Publisher
   */
  publisher: string
  /**
   * Retrieved At
   */
  retrieved_at: string
}

/**
 * JobStatus
 *
 * Explicit job states visible to the authorized owner.
 */
export type JobStatus =
  | "accepted"
  | "researching"
  | "drafting"
  | "validating"
  | "rendering"
  | "delivering"
  | "completed"
  | "failed"
  | "cancelled"

/**
 * JobStatusPublic
 *
 * Complete owner-scoped polling response built from one package snapshot.
 */
export type JobStatusPublic = {
  /**
   * Schema Version
   */
  schema_version: "1.0"
  /**
   * Job Id
   */
  job_id: string
  status: JobStatus
  /**
   * Revision
   */
  revision: number
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  progress: JobProgressPublic
  input: JobInputPublic
  failure: JobFailurePublic | null
  result: JobResultPublic | null
  artifacts: JobArtifactAvailabilityPublic
}

/**
 * JobSubmissionRequest
 *
 * Strict JSON request with one discriminated source input.
 */
export type JobSubmissionRequest = {
  preferences: JobPreferences
  /**
   * Consent To Ai Processing
   */
  consent_to_ai_processing: true
  learner_age_group: JobLearnerAgeGroup
  /**
   * Input
   */
  input:
    | ({
        type: "prompt"
      } & PromptJobInput)
    | ({
        type: "text"
      } & TextJobInput)
    | ({
        type: "url"
      } & UrlJobInput)
    | ({
        type: "youtube"
      } & YouTubeJobInput)
}

/**
 * Message
 */
export type Message = {
  /**
   * Message
   */
  message: string
}

/**
 * NewPassword
 *
 * Request body for password reset completion.
 *
 * Submitted after user clicks the password reset link. Token is from
 * the email link, new_password must meet strength requirements.
 */
export type NewPassword = {
  /**
   * Token
   */
  token: string
  /**
   * New Password
   */
  new_password: string
}

/**
 * PasswordRecoveryRequest
 *
 * Request body for initiating password recovery.
 *
 * Uses JSON body input (instead of URL path parameters) to avoid exposing
 * email addresses in route paths captured by access logs and browser history.
 */
export type PasswordRecoveryRequest = {
  /**
   * Email
   */
  email: string
}

/**
 * PromptJobInput
 *
 * A short topic or course-generation instruction.
 */
export type PromptJobInput = {
  /**
   * Type
   */
  type: "prompt"
  /**
   * Value
   */
  value: string
}

/**
 * PublicFailureCode
 *
 * Reviewed stable failure categories the application may translate.
 */
export type PublicFailureCode =
  | "provider_consent_required"
  | "age_inappropriate"
  | "copyright_reproduction"
  | "high_risk_review_required"
  | "stage_not_accepted"
  | "generation_failed"
  | "cancelled"

/**
 * ReadinessCheckState
 *
 * Coarse state for one safe shell readiness dimension.
 */
export type ReadinessCheckState = "ready" | "unavailable"

/**
 * ReadinessStatus
 *
 * Overall cached state presented to later API schemas.
 */
export type ReadinessStatus = "ready" | "degraded" | "unavailable"

/**
 * SystemAuthenticationPublic
 *
 * Validated challenge or terminal state with no account/token data.
 */
export type SystemAuthenticationPublic = {
  state: SystemAuthenticationState
  /**
   * Verification Url
   */
  verification_url: string | null
  /**
   * User Code
   */
  user_code: string | null
  /**
   * Message
   */
  message: string
}

/**
 * SystemAuthenticationState
 *
 * Safe states that an application setup screen may display.
 */
export type SystemAuthenticationState =
  | "signed_out"
  | "waiting_for_user"
  | "authenticated"
  | "failed"

/**
 * SystemInputMode
 *
 * Finite P0 input modes the generated client may display.
 */
export type SystemInputMode =
  | "prompt"
  | "text"
  | "url"
  | "youtube"
  | "pdf"
  | "document"
  | "slides"

/**
 * SystemReadinessChecksPublic
 *
 * Coarse dimensions with no infrastructure or provider detail.
 */
export type SystemReadinessChecksPublic = {
  authentication: ReadinessCheckState
  model: ReadinessCheckState
  research: ReadinessCheckState
  storage: ReadinessCheckState
  worker: ReadinessCheckState
  inputs: ReadinessCheckState
  admission: ReadinessCheckState
  runtime_ownership: ReadinessCheckState
}

/**
 * SystemReadinessPublic
 *
 * HTTP projection of one immutable side-effect-free readiness snapshot.
 */
export type SystemReadinessPublic = {
  /**
   * Schema Version
   */
  schema_version: "1.0"
  status: ReadinessStatus
  /**
   * Accepting Jobs
   */
  accepting_jobs: boolean
  /**
   * Configured Model Id
   */
  configured_model_id:
    | "gpt-5.6"
    | "gpt-5.6-sol"
    | "gpt-5.6-terra"
    | "gpt-5.6-luna"
  /**
   * Enabled Input Modes
   */
  enabled_input_modes: Array<SystemInputMode>
  checks: SystemReadinessChecksPublic
  /**
   * Warnings
   */
  warnings: Array<string>
  /**
   * Recovery Actions
   */
  recovery_actions: Array<string>
  /**
   * Checked At
   */
  checked_at: string
  /**
   * Is Fresh
   */
  is_fresh: boolean
}

/**
 * TextJobInput
 *
 * Finite learner-pasted source text.
 */
export type TextJobInput = {
  /**
   * Type
   */
  type: "text"
  /**
   * Value
   */
  value: string
}

/**
 * Token
 */
export type Token = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Token Type
   */
  token_type?: string
}

/**
 * UpdatePassword
 *
 * Request body for password change.
 *
 * Requires both current password (for verification) and new password.
 * Both must meet the 8-128 character length requirement.
 */
export type UpdatePassword = {
  /**
   * Current Password
   */
  current_password: string
  /**
   * New Password
   */
  new_password: string
}

/**
 * UrlJobInput
 *
 * A public URL whose safety and retrieval remain package-owned.
 */
export type UrlJobInput = {
  /**
   * Value
   */
  value: string
  /**
   * Type
   */
  type: "url"
}

/**
 * UserCreate
 *
 * Request body for creating a new user (admin endpoint).
 *
 * Validates email format, password strength, and rejects unknown fields.
 * Used by superusers to create new user accounts with optional permissions.
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string
  /**
   * Is Active
   */
  is_active?: boolean
  /**
   * Is Superuser
   */
  is_superuser?: boolean
  /**
   * Full Name
   */
  full_name?: string | null
  /**
   * Password
   */
  password: string
}

/**
 * UserPublic
 */
export type UserPublic = {
  /**
   * Email
   */
  email: string
  /**
   * Is Active
   */
  is_active?: boolean
  /**
   * Is Superuser
   */
  is_superuser?: boolean
  /**
   * Full Name
   */
  full_name?: string | null
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at?: string | null
}

/**
 * UserRegister
 *
 * Request body for user self-registration.
 *
 * Public endpoint schema with strict validation. Users cannot set
 * is_active or is_superuser flags during registration.
 */
export type UserRegister = {
  /**
   * Email
   */
  email: string
  /**
   * Password
   */
  password: string
  /**
   * Full Name
   */
  full_name?: string | null
}

/**
 * UserUpdate
 *
 * Request body for updating a user (admin endpoint).
 *
 * All fields are optional. Superusers can update any user's details
 * including email, password, and permission flags.
 */
export type UserUpdate = {
  /**
   * Email
   */
  email?: string | null
  /**
   * Is Active
   */
  is_active?: boolean
  /**
   * Is Superuser
   */
  is_superuser?: boolean
  /**
   * Full Name
   */
  full_name?: string | null
  /**
   * Password
   */
  password?: string | null
}

/**
 * UserUpdateMe
 *
 * Request body for users updating their own profile.
 *
 * Limited to non-privileged fields (full_name, email). Users cannot
 * change their own is_active or is_superuser status.
 */
export type UserUpdateMe = {
  /**
   * Full Name
   */
  full_name?: string | null
  /**
   * Email
   */
  email?: string | null
}

/**
 * UsersPublic
 */
export type UsersPublic = {
  /**
   * Data
   */
  data: Array<UserPublic>
  /**
   * Count
   */
  count: number
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

/**
 * YouTubeJobInput
 *
 * YouTube intent routed through the package URL adapter.
 */
export type YouTubeJobInput = {
  /**
   * Value
   */
  value: string
  /**
   * Type
   */
  type: "youtube"
}

export type PostApiV1LoginAccessTokenData = {
  body: BodyLoginLoginAccessToken
  path?: never
  query?: never
  url: "/api/v1/login/access-token"
}

export type PostApiV1LoginAccessTokenErrors = {
  /**
   * Invalid credentials or inactive user
   */
  400: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
  /**
   * Rate limit exceeded
   */
  429: unknown
}

export type PostApiV1LoginAccessTokenError =
  PostApiV1LoginAccessTokenErrors[keyof PostApiV1LoginAccessTokenErrors]

export type PostApiV1LoginAccessTokenResponses = {
  /**
   * Successfully authenticated
   */
  200: Token
}

export type PostApiV1LoginAccessTokenResponse =
  PostApiV1LoginAccessTokenResponses[keyof PostApiV1LoginAccessTokenResponses]

export type PostApiV1LoginTestTokenData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/login/test-token"
}

export type PostApiV1LoginTestTokenErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Invalid or expired token
   */
  403: unknown
}

export type PostApiV1LoginTestTokenResponses = {
  /**
   * Token is valid, returns user data
   */
  200: UserPublic
}

export type PostApiV1LoginTestTokenResponse =
  PostApiV1LoginTestTokenResponses[keyof PostApiV1LoginTestTokenResponses]

export type PostApiV1PasswordRecoveryData = {
  body: PasswordRecoveryRequest
  path?: never
  query?: never
  url: "/api/v1/password-recovery"
}

export type PostApiV1PasswordRecoveryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
  /**
   * Rate limit exceeded
   */
  429: unknown
}

export type PostApiV1PasswordRecoveryError =
  PostApiV1PasswordRecoveryErrors[keyof PostApiV1PasswordRecoveryErrors]

export type PostApiV1PasswordRecoveryResponses = {
  /**
   * Generic password recovery response
   */
  200: Message
}

export type PostApiV1PasswordRecoveryResponse =
  PostApiV1PasswordRecoveryResponses[keyof PostApiV1PasswordRecoveryResponses]

export type PostApiV1ResetPasswordData = {
  body: NewPassword
  path?: never
  query?: never
  url: "/api/v1/reset-password/"
}

export type PostApiV1ResetPasswordErrors = {
  /**
   * Invalid or expired token
   */
  401: unknown
  /**
   * User account is inactive
   */
  403: unknown
  /**
   * Validation error (password requirements not met)
   */
  422: unknown
  /**
   * Rate limit exceeded
   */
  429: unknown
}

export type PostApiV1ResetPasswordResponses = {
  /**
   * Password successfully updated
   */
  200: Message
}

export type PostApiV1ResetPasswordResponse =
  PostApiV1ResetPasswordResponses[keyof PostApiV1ResetPasswordResponses]

export type PostApiV1PasswordRecoveryHtmlContentByEmailData = {
  body?: never
  path: {
    /**
     * Email
     *
     * Email address of the user to generate recovery email for
     */
    email: string
  }
  query?: never
  url: "/api/v1/password-recovery-html-content/{email}"
}

export type PostApiV1PasswordRecoveryHtmlContentByEmailErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough privileges (superuser required)
   */
  403: unknown
  /**
   * User not found
   */
  404: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PostApiV1PasswordRecoveryHtmlContentByEmailError =
  PostApiV1PasswordRecoveryHtmlContentByEmailErrors[keyof PostApiV1PasswordRecoveryHtmlContentByEmailErrors]

export type PostApiV1PasswordRecoveryHtmlContentByEmailResponses = {
  /**
   * HTML email content returned
   */
  200: string
}

export type PostApiV1PasswordRecoveryHtmlContentByEmailResponse =
  PostApiV1PasswordRecoveryHtmlContentByEmailResponses[keyof PostApiV1PasswordRecoveryHtmlContentByEmailResponses]

export type GetApiV1UsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     *
     * Number of users to skip for pagination
     */
    skip?: number
    /**
     * Limit
     *
     * Maximum number of users to return (1-100)
     */
    limit?: number
  }
  url: "/api/v1/users/"
}

export type GetApiV1UsersErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough privileges (superuser required)
   */
  403: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetApiV1UsersError = GetApiV1UsersErrors[keyof GetApiV1UsersErrors]

export type GetApiV1UsersResponses = {
  /**
   * Successfully retrieved users
   */
  200: UsersPublic
}

export type GetApiV1UsersResponse =
  GetApiV1UsersResponses[keyof GetApiV1UsersResponses]

export type PostApiV1UsersData = {
  body: UserCreate
  path?: never
  query?: never
  url: "/api/v1/users/"
}

export type PostApiV1UsersErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough privileges (superuser required)
   */
  403: unknown
  /**
   * User with this email already exists
   */
  409: unknown
  /**
   * Validation error in request body
   */
  422: unknown
}

export type PostApiV1UsersResponses = {
  /**
   * User successfully created
   */
  201: UserPublic
}

export type PostApiV1UsersResponse =
  PostApiV1UsersResponses[keyof PostApiV1UsersResponses]

export type DeleteApiV1UsersMeData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type DeleteApiV1UsersMeErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Superusers cannot delete themselves
   */
  403: unknown
}

export type DeleteApiV1UsersMeResponses = {
  /**
   * Account successfully deleted
   */
  200: Message
}

export type DeleteApiV1UsersMeResponse =
  DeleteApiV1UsersMeResponses[keyof DeleteApiV1UsersMeResponses]

export type GetApiV1UsersMeData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type GetApiV1UsersMeErrors = {
  /**
   * Not authenticated
   */
  401: unknown
}

export type GetApiV1UsersMeResponses = {
  /**
   * Current user profile
   */
  200: UserPublic
}

export type GetApiV1UsersMeResponse =
  GetApiV1UsersMeResponses[keyof GetApiV1UsersMeResponses]

export type PatchApiV1UsersMeData = {
  body: UserUpdateMe
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type PatchApiV1UsersMeErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * User with this email already exists
   */
  409: unknown
  /**
   * Validation error in request body
   */
  422: unknown
}

export type PatchApiV1UsersMeResponses = {
  /**
   * Profile successfully updated
   */
  200: UserPublic
}

export type PatchApiV1UsersMeResponse =
  PatchApiV1UsersMeResponses[keyof PatchApiV1UsersMeResponses]

export type PatchApiV1UsersMePasswordData = {
  body: UpdatePassword
  path?: never
  query?: never
  url: "/api/v1/users/me/password"
}

export type PatchApiV1UsersMePasswordErrors = {
  /**
   * Invalid current password or new password same as current
   */
  400: unknown
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Validation error in request body
   */
  422: unknown
}

export type PatchApiV1UsersMePasswordResponses = {
  /**
   * Password successfully updated
   */
  200: Message
}

export type PatchApiV1UsersMePasswordResponse =
  PatchApiV1UsersMePasswordResponses[keyof PatchApiV1UsersMePasswordResponses]

export type PostApiV1UsersSignupData = {
  body: UserRegister
  path?: never
  query?: never
  url: "/api/v1/users/signup"
}

export type PostApiV1UsersSignupErrors = {
  /**
   * Public signup is disabled
   */
  403: unknown
  /**
   * User with this email already exists
   */
  409: unknown
  /**
   * Validation error in request body
   */
  422: unknown
  /**
   * Rate limit exceeded
   */
  429: unknown
}

export type PostApiV1UsersSignupResponses = {
  /**
   * User successfully registered
   */
  201: UserPublic
}

export type PostApiV1UsersSignupResponse =
  PostApiV1UsersSignupResponses[keyof PostApiV1UsersSignupResponses]

export type DeleteApiV1UsersByUserIdData = {
  body?: never
  path: {
    /**
     * User Id
     *
     * Unique identifier of the user to delete
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/users/{user_id}"
}

export type DeleteApiV1UsersByUserIdErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough privileges or attempting self-deletion
   */
  403: unknown
  /**
   * User not found
   */
  404: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteApiV1UsersByUserIdError =
  DeleteApiV1UsersByUserIdErrors[keyof DeleteApiV1UsersByUserIdErrors]

export type DeleteApiV1UsersByUserIdResponses = {
  /**
   * User successfully deleted
   */
  200: Message
}

export type DeleteApiV1UsersByUserIdResponse =
  DeleteApiV1UsersByUserIdResponses[keyof DeleteApiV1UsersByUserIdResponses]

export type GetApiV1UsersByUserIdData = {
  body?: never
  path: {
    /**
     * User Id
     *
     * Unique identifier of the user
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/users/{user_id}"
}

export type GetApiV1UsersByUserIdErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough privileges to access this user
   */
  403: unknown
  /**
   * User not found
   */
  404: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetApiV1UsersByUserIdError =
  GetApiV1UsersByUserIdErrors[keyof GetApiV1UsersByUserIdErrors]

export type GetApiV1UsersByUserIdResponses = {
  /**
   * User successfully retrieved
   */
  200: UserPublic
}

export type GetApiV1UsersByUserIdResponse =
  GetApiV1UsersByUserIdResponses[keyof GetApiV1UsersByUserIdResponses]

export type PatchApiV1UsersByUserIdData = {
  body: UserUpdate
  path: {
    /**
     * User Id
     *
     * Unique identifier of the user to update
     */
    user_id: string
  }
  query?: never
  url: "/api/v1/users/{user_id}"
}

export type PatchApiV1UsersByUserIdErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough privileges (superuser required)
   */
  403: unknown
  /**
   * User not found
   */
  404: unknown
  /**
   * User with this email already exists
   */
  409: unknown
  /**
   * Validation error in request body
   */
  422: unknown
}

export type PatchApiV1UsersByUserIdResponses = {
  /**
   * User successfully updated
   */
  200: UserPublic
}

export type PatchApiV1UsersByUserIdResponse =
  PatchApiV1UsersByUserIdResponses[keyof PatchApiV1UsersByUserIdResponses]

export type PostApiV1UtilsTestEmailData = {
  body?: never
  path?: never
  query: {
    /**
     * Email To
     */
    email_to: string
  }
  url: "/api/v1/utils/test-email/"
}

export type PostApiV1UtilsTestEmailErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PostApiV1UtilsTestEmailError =
  PostApiV1UtilsTestEmailErrors[keyof PostApiV1UtilsTestEmailErrors]

export type PostApiV1UtilsTestEmailResponses = {
  /**
   * Successful Response
   */
  201: Message
}

export type PostApiV1UtilsTestEmailResponse =
  PostApiV1UtilsTestEmailResponses[keyof PostApiV1UtilsTestEmailResponses]

export type GetApiV1UtilsHealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/utils/health-check/"
}

export type GetApiV1UtilsHealthCheckResponses = {
  /**
   * Response Utils-Health Check
   *
   * Successful Response
   */
  200: boolean
}

export type GetApiV1UtilsHealthCheckResponse =
  GetApiV1UtilsHealthCheckResponses[keyof GetApiV1UtilsHealthCheckResponses]

export type GetApiV1UtilsHealthData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/utils/health/"
}

export type GetApiV1UtilsHealthResponses = {
  /**
   * Successful Response
   */
  200: HealthCheckResponse
}

export type GetApiV1UtilsHealthResponse =
  GetApiV1UtilsHealthResponses[keyof GetApiV1UtilsHealthResponses]

export type GetApiV1ItemsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     *
     * Number of items to skip for pagination
     */
    skip?: number
    /**
     * Limit
     *
     * Maximum number of items to return (1-100)
     */
    limit?: number
    /**
     * Content Type
     *
     * Filter by content type
     */
    content_type?: "general" | null
  }
  url: "/api/v1/items/"
}

export type GetApiV1ItemsErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetApiV1ItemsError = GetApiV1ItemsErrors[keyof GetApiV1ItemsErrors]

export type GetApiV1ItemsResponses = {
  /**
   * Successfully retrieved items
   */
  200: ItemsPublic
}

export type GetApiV1ItemsResponse =
  GetApiV1ItemsResponses[keyof GetApiV1ItemsResponses]

export type PostApiV1ItemsData = {
  body: ItemCreate
  path?: never
  query?: never
  url: "/api/v1/items/"
}

export type PostApiV1ItemsErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Validation error in request body
   */
  422: unknown
}

export type PostApiV1ItemsResponses = {
  /**
   * Item successfully created
   */
  201: ItemPublic
}

export type PostApiV1ItemsResponse =
  PostApiV1ItemsResponses[keyof PostApiV1ItemsResponses]

export type DeleteApiV1ItemsByIdData = {
  body?: never
  path: {
    /**
     * Id
     *
     * Unique identifier of the item to delete
     */
    id: string
  }
  query?: never
  url: "/api/v1/items/{id}"
}

export type DeleteApiV1ItemsByIdErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough permissions to delete this item
   */
  403: unknown
  /**
   * Item not found
   */
  404: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteApiV1ItemsByIdError =
  DeleteApiV1ItemsByIdErrors[keyof DeleteApiV1ItemsByIdErrors]

export type DeleteApiV1ItemsByIdResponses = {
  /**
   * Item successfully deleted
   */
  200: Message
}

export type DeleteApiV1ItemsByIdResponse =
  DeleteApiV1ItemsByIdResponses[keyof DeleteApiV1ItemsByIdResponses]

export type GetApiV1ItemsByIdData = {
  body?: never
  path: {
    /**
     * Id
     *
     * Unique identifier of the item
     */
    id: string
  }
  query?: never
  url: "/api/v1/items/{id}"
}

export type GetApiV1ItemsByIdErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough permissions to access this item
   */
  403: unknown
  /**
   * Item not found
   */
  404: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetApiV1ItemsByIdError =
  GetApiV1ItemsByIdErrors[keyof GetApiV1ItemsByIdErrors]

export type GetApiV1ItemsByIdResponses = {
  /**
   * Item successfully retrieved
   */
  200: ItemPublic
}

export type GetApiV1ItemsByIdResponse =
  GetApiV1ItemsByIdResponses[keyof GetApiV1ItemsByIdResponses]

export type PutApiV1ItemsByIdData = {
  body: ItemUpdate
  path: {
    /**
     * Id
     *
     * Unique identifier of the item to update
     */
    id: string
  }
  query?: never
  url: "/api/v1/items/{id}"
}

export type PutApiV1ItemsByIdErrors = {
  /**
   * Not authenticated
   */
  401: unknown
  /**
   * Not enough permissions to update this item
   */
  403: unknown
  /**
   * Item not found
   */
  404: unknown
  /**
   * Validation error in request body
   */
  422: unknown
}

export type PutApiV1ItemsByIdResponses = {
  /**
   * Item successfully updated
   */
  200: ItemPublic
}

export type PutApiV1ItemsByIdResponse =
  PutApiV1ItemsByIdResponses[keyof PutApiV1ItemsByIdResponses]

export type PostApiV1JobsData = {
  body: JobSubmissionRequest
  headers: {
    /**
     * Idempotency-Key
     *
     * Private owner-scoped retry key. Reuse only when retrying the same exact course request.
     */
    "Idempotency-Key": string
  }
  path?: never
  query?: never
  url: "/api/v1/jobs"
}

export type PostApiV1JobsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PostApiV1JobsError = PostApiV1JobsErrors[keyof PostApiV1JobsErrors]

export type PostApiV1JobsResponses = {
  /**
   * Successful Response
   */
  202: JobAcceptedPublic
}

export type PostApiV1JobsResponse =
  PostApiV1JobsResponses[keyof PostApiV1JobsResponses]

export type PostApiV1JobsUploadData = {
  body: BodyJobsSubmitJobUpload
  headers: {
    /**
     * Idempotency-Key
     *
     * Private owner-scoped retry key. Reuse only when retrying the same exact course request.
     */
    "Idempotency-Key": string
  }
  path?: never
  query?: never
  url: "/api/v1/jobs/upload"
}

export type PostApiV1JobsUploadErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type PostApiV1JobsUploadError =
  PostApiV1JobsUploadErrors[keyof PostApiV1JobsUploadErrors]

export type PostApiV1JobsUploadResponses = {
  /**
   * Successful Response
   */
  202: JobAcceptedPublic
}

export type PostApiV1JobsUploadResponse =
  PostApiV1JobsUploadResponses[keyof PostApiV1JobsUploadResponses]

export type GetApiV1JobsByJobIdData = {
  body?: never
  path: {
    /**
     * Job Id
     *
     * Opaque owner-scoped durable course job identifier.
     */
    job_id: string
  }
  query?: never
  url: "/api/v1/jobs/{job_id}"
}

export type GetApiV1JobsByJobIdErrors = {
  /**
   * Authentication is required.
   */
  401: unknown
  /**
   * The owner-scoped course job was not found.
   */
  404: unknown
  /**
   * A path identifier is invalid.
   */
  422: unknown
  /**
   * The course result could not be read safely.
   */
  500: unknown
}

export type GetApiV1JobsByJobIdResponses = {
  /**
   * Successful Response
   */
  200: JobStatusPublic
}

export type GetApiV1JobsByJobIdResponse =
  GetApiV1JobsByJobIdResponses[keyof GetApiV1JobsByJobIdResponses]

export type GetApiV1JobsByJobIdArtifactsData = {
  body?: never
  path: {
    /**
     * Job Id
     *
     * Opaque owner-scoped durable course job identifier.
     */
    job_id: string
  }
  query?: never
  url: "/api/v1/jobs/{job_id}/artifacts"
}

export type GetApiV1JobsByJobIdArtifactsErrors = {
  /**
   * Authentication is required.
   */
  401: unknown
  /**
   * The owner-scoped course job was not found.
   */
  404: unknown
  /**
   * A path identifier is invalid.
   */
  422: unknown
  /**
   * The course result could not be read safely.
   */
  500: unknown
}

export type GetApiV1JobsByJobIdArtifactsResponses = {
  /**
   * Successful Response
   */
  200: ArtifactManifestPublic
}

export type GetApiV1JobsByJobIdArtifactsResponse =
  GetApiV1JobsByJobIdArtifactsResponses[keyof GetApiV1JobsByJobIdArtifactsResponses]

export type GetApiV1JobsByJobIdArtifactsByArtifactIdData = {
  body?: never
  path: {
    /**
     * Job Id
     *
     * Opaque owner-scoped durable course job identifier.
     */
    job_id: string
    /**
     * Artifact Id
     *
     * Stable canonical artifact identifier.
     */
    artifact_id: string
  }
  query?: never
  url: "/api/v1/jobs/{job_id}/artifacts/{artifact_id}"
}

export type GetApiV1JobsByJobIdArtifactsByArtifactIdErrors = {
  /**
   * Authentication is required.
   */
  401: unknown
  /**
   * The owner-scoped course job was not found.
   */
  404: unknown
  /**
   * A path identifier is invalid.
   */
  422: unknown
  /**
   * The course result could not be read safely.
   */
  500: unknown
}

export type GetApiV1JobsByJobIdArtifactsByArtifactIdResponses = {
  /**
   * Verified private artifact bytes.
   */
  200: string | Blob | File
}

export type GetApiV1JobsByJobIdArtifactsByArtifactIdResponse =
  GetApiV1JobsByJobIdArtifactsByArtifactIdResponses[keyof GetApiV1JobsByJobIdArtifactsByArtifactIdResponses]

export type GetApiV1SystemReadinessData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/system/readiness"
}

export type GetApiV1SystemReadinessResponses = {
  /**
   * Successful Response
   */
  200: SystemReadinessPublic
}

export type GetApiV1SystemReadinessResponse =
  GetApiV1SystemReadinessResponses[keyof GetApiV1SystemReadinessResponses]

export type PostApiV1SystemAuthStartData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/system/auth/start"
}

export type PostApiV1SystemAuthStartResponses = {
  /**
   * Successful Response
   */
  200: SystemAuthenticationPublic
}

export type PostApiV1SystemAuthStartResponse =
  PostApiV1SystemAuthStartResponses[keyof PostApiV1SystemAuthStartResponses]

export type GetApiV1SystemAuthStatusData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/system/auth/status"
}

export type GetApiV1SystemAuthStatusResponses = {
  /**
   * Successful Response
   */
  200: SystemAuthenticationPublic
}

export type GetApiV1SystemAuthStatusResponse =
  GetApiV1SystemAuthStatusResponses[keyof GetApiV1SystemAuthStatusResponses]
