"""add_item_content_fields

Revision ID: 4ac9cd0948d7
Revises: 1a31ce608336
Create Date: 2025-12-22 15:55:42.797201

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision = '4ac9cd0948d7'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    op.add_column('item', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('item', sa.Column('content_type', sa.String(length=50), nullable=True))
    op.add_column('item', sa.Column('item_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_metadata')
    op.drop_column('item', 'content_type')
    op.drop_column('item', 'content')
    op.drop_column('item', 'source_url')
    # ### end Alembic commands ###
