name: Test Docker Compose

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:

  test-docker-compose:
    name: Test the Compose application
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: docker compose build
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d --wait backend frontend adminer
      - name: Test backend readiness
        run: curl --fail http://localhost:8012/api/v1/utils/health/
      - name: Test frontend health
        run: curl --fail http://localhost:5183/health
      - if: always()
        run: docker compose down -v --remove-orphans
